server:
  #服务的HTTP端口
  port: 1111 


spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: HYPHYPHYP123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        #连接池中的最大连接活跃数
        maxActive: 20
        #在连接池启动时要建立的连接数
        initialSize: 1
        #连接池在等待返回连接时，最长等待时间多少毫秒再抛出异常  
        maxWait: 60000
        #连接池中的最大连接空闲数
        minIdle: 1
        #在两次空闲连接验证、弃用连接清理和空闲池大小调整之间睡眠的毫秒数
        timeBetweenEvictionRunsMillis: 60000
        #一个空闲连接被空闲连接释放器（如果存在的话）优雅的释放前，最短会在连接池中停留多长时间
        minEvictableIdleTimeMillis: 300000
        #在连接池里的连接返回给调用者或连接池时，要执行的验证SQL查询
        validationQuery: select 'x'
        #在连接空闲时是否进行测试
        testWhileIdle: true
        #从连接池中借用连接时是否要进行测试
        testOnBorrow: false
        #在将连接归还到连接池时是否要进行测试
        testOnReturn: false
        #是否要将Statement放在池里
        poolPreparedStatements: true
        #是否缓存preparedStatement，也就是PSCache，连接最大数
        maxPoolPreparedStatementPerConnectionSize: 20
        #开启状态的PreparedStatement的数量上限
        maxOpenPreparedStatements: 20
    thymeleaf:
            #在构建URL时添加到视图名称前的前缀。（默认值：classpath:/templates/）
            prefix: classpath:/templates/
            #检查模板位置是否存在。（默认：true）
            check-template-location: true
            #在构建URL时添加到视图名称后的后缀。（默认值：.html）
            suffix: .html
            #模板编码。（默认值： UTF-8）
            encoding: UTF-8
            #要运用于模板之上的模板模式。（默认值：HTML5）
            mode: LEGACYHTML5
            #开启模板缓存。（默认值：true）
            cache: false
    aop:
      #添加@EnableAspectJAutoProxy。（默认值：true）
      auto: true
      #是否要创建基于子类（即Dode Generation Library, CGLIB）的代理来代替基于java接口的代理，前者为true，后者为false。（默认值：false）
      proxy-target-class: true
    servlet:
          multipart:
            #上传文件的最大值。（默认值：1MB）
            max-file-size: 10Mb
            #最大请求大小。（默认值：10MB）
            max-request-size: 100Mb
mybatis:
  #mapper映射文件的所在位置
  mapper-locations: classpath:mapper/*.xml
  #pojo类所在位置
  type-aliases-package: com.hyp.model

mapper:
  mappers:  com.hyp.dao
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    #数据库类型
    helperDialect: mysql
    #分页参数合理化，默认false禁用
    reasonable: true
    #默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
    supportMethodsArguments: true
    #用于从对象中根据属性名取值
    params: count=countSql
    #always总是返回PageInfo类型,check检查返回类型是否为PageInfo,none返回Page
    returnPageInfo: check
 
logging:
  level:
    com.hyp.dao : DEBUG

swagger:
  show: true